name:                qrcode-core
version:             0.9.7
github:              "alexkazik/qrcode"
license:             MIT
author:              "ALeX Kazik"
maintainer:          "alex@kazik.de"
copyright:           "2018 ALeX Kazik"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            QR code library in pure Haskell
category:            codec

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/alexkazik/qrcode/qrcode-core#readme>

dependencies:
- base >= 4.8.2.0 && < 5
- binary >= 0.7.5.0 && < 0.9
- bytestring >= 0.10.6.0 && < 0.12
- case-insensitive >= 1.2.0.5 && < 1.3
- containers >= 0.5.6.2 && < 0.7
- dlist >= 0.7.1.2 && < 1.1
- primitive >= 0.6.1.0 && < 0.8
- text >= 1.2.2.0 && < 2.1
- vector >= 0.11.0.0 && < 0.14

when:
  - condition: impl(ghc < 8)
    dependencies: semigroups

library:
  source-dirs: src
  exposed-modules:
  - Codec.QRCode
  - Codec.QRCode.Intermediate
  - Codec.QRCode.Intermediate.Special
  - Codec.QRCode.Data.ErrorLevel
  - Codec.QRCode.Data.Mask
  - Codec.QRCode.Data.QRImage
  - Codec.QRCode.Data.QRCodeOptions
  - Codec.QRCode.Data.QRIntermediate
  - Codec.QRCode.Data.QRSegment
  - Codec.QRCode.Data.Result
  - Codec.QRCode.Data.TextEncoding
  - Codec.QRCode.Data.ToInput

tested-with:
  GHC == 7.10.3,
  GHC == 8.0.1,
  GHC == 8.0.2,
  GHC == 8.2.2,
  GHC == 8.4.3,
  GHC == 8.4.4,
  GHC == 8.6.3,
  GHC == 8.6.4,
  GHC == 8.6.5,
  GHC == 8.8.2,
  GHC == 8.8.3,
  GHC == 8.10.1,
  GHC == 8.10.7,
  GHC == 9.4.4
