name:                qrcode-juicypixels
version:             0.8.5
github:              "alexkazik/qrcode"
license:             MIT
author:              "ALeX Kazik"
maintainer:          "alex@kazik.de"
copyright:           "2018 ALeX Kazik"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Converts a qrcode-core image to JuicyPixels
category:            graphics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/alexkazik/qrcode/qrcode-juicypixels#readme>

dependencies:
- base >= 4.8.2.0 && < 5
- base64-bytestring >= 1.0.0.1 && < 1.3
- bytestring >= 0.10.6.0 && < 0.12
- JuicyPixels >= 3.2.6 && < 3.4
- qrcode-core >= 0.8 && < 1
- text >= 1.2.2.0 && < 2.2
- vector >= 0.11.0.0 && < 0.14

library:
  source-dirs: src

tested-with:
  GHC == 7.10.3,
  GHC == 8.0.1,
  GHC == 8.0.2,
  GHC == 8.2.2,
  GHC == 8.4.3,
  GHC == 8.10.7,
  GHC == 9.4.4
